version: "2.2"
services:
  sql-client:
    container_name: 'flink-sql-client'
    build:
      context: .
      dockerfile: sql-client/Dockerfile
    depends_on:
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
    volumes:
      - ./flink/settings/:/settings
    networks:
      - pizza-shop
  jobmanager:
    image: flink:1.16.0-scala_2.12-java11
    container_name: 'flink-jobmanager'
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 30
    volumes:
      - ./flink/settings/:/settings
      - ./flink/data/:/data
    networks:
      - pizza-shop
  taskmanager:
    image: flink:1.16.0-scala_2.12-java11
    container_name: 'flink-taskmanager'
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 30
    volumes:
      - ./flink/settings/:/settings
      - ./flink/data/:/data
    networks:
      - pizza-shop
networks:
  pizza-shop:
    name: pizza-shop